Repository callstack/react-native-paper, pull requests merged in 2019-04, with the labels that each got.

#976 fix: rewrite of menu component
  src/components/Menu/Menu.js
  src/components/__tests__/Menu.test.js
  src/components/__tests__/__snapshots__/Menu.test.js.snap
Labels: core team

#942 feat: add scale to control modal animation speed
  src/components/Modal.js
  src/components/__tests__/__snapshots__/ListSection.test.js.snap
  src/styles/DefaultTheme.js
  src/types.js
Labels: 3.0, core team

#735 feat: ProgressBar component
  example/src/Examples/ProgressBarExample.js
  src/components/ProgressBar.js
  src/components/ProgressBar/ProgressBar.js
  src/components/ProgressBar/ProgressBarComponent.android.js
  src/components/ProgressBar/ProgressBarComponent.ios.js
  src/components/ProgressBar/ProgressBarComponent.js
  src/components/ProgressBar/ProgressBarComponent.macos.js
  src/components/ProgressBar/ProgressBarComponent.windows.js
  src/components/__tests__/ProgressBar.test.js
  src/components/__tests__/__snapshots__/ProgressBar.test.js.snap
  src/index.js
  typings/components/ProgressBar.d.ts
Labels: 3.0, breaking change

#915 feat: BREAKING CHANGE replace any with proper types
  src/components/ActivityIndicator.js
  src/components/Appbar/Appbar.js
  src/components/Appbar/AppbarAction.js
  src/components/Appbar/AppbarBackAction.js
  src/components/Appbar/AppbarContent.js
  src/components/Appbar/AppbarHeader.js
  src/components/Avatar/AvatarIcon.js
  src/components/Avatar/AvatarImage.js
  src/components/Avatar/AvatarText.js
  src/components/Badge.js
  src/components/Banner.js
  src/components/BottomNavigation.js
  src/components/Button.js
  src/components/Card/Card.js
  src/components/Card/CardActions.js
  src/components/Card/CardContent.js
  src/components/Card/CardCover.js
  src/components/Card/CardTitle.js
  src/components/Chip.js
  src/components/DataTable/DataTable.js
  src/components/DataTable/DataTableCell.js
  src/components/DataTable/DataTableHeader.js
  src/components/DataTable/DataTablePagination.js
  src/components/DataTable/DataTableRow.js
  src/components/DataTable/DataTableTitle.js
  src/components/Dialog/Dialog.js
  src/components/Dialog/DialogActions.js
  src/components/Dialog/DialogContent.js
  src/components/Dialog/DialogScrollArea.js
  src/components/Dialog/DialogTitle.js
  src/components/Divider.js
  src/components/Drawer/DrawerItem.js
  src/components/FAB/FAB.js
  src/components/FAB/FABGroup.js
  src/components/HelperText.js
  src/components/IconButton.js
  src/components/List/ListAccordion.js
  src/components/List/ListIcon.js
  src/components/List/ListSection.js
  src/components/List/ListSubheader.js
  src/components/Modal.js
  src/components/Searchbar.js
  src/components/Snackbar.js
  src/components/Switch.js
  src/components/ToggleButton/ToggleButton.js
  src/components/TouchableRipple/index.js
  src/components/TouchableRipple/index.native.js
  src/components/Typography/Title.js
Labels: 3.0, core team

#1014 fix: use theme font in TextInputFlat
  src/components/TextInput/TextInputFlat.js
  src/components/TextInput/TextInputOutlined.js
Labels: 3.0, bug
