Repository callstack/react-native-paper, pull requests merged in 2019-03, with the labels that each got.

#912 fix: make sure to remove BackHandler listener on Modal
  src/components/Modal.js
Labels: core team

#911 feat: add titleStyle and descriptionStyle props to List.Item
  src/components/List/ListItem.js
  src/components/__tests__/ListItem.test.js
  src/components/__tests__/__snapshots__/ListAccordion.test.js.snap
  src/components/__tests__/__snapshots__/ListItem.test.js.snap
  src/components/__tests__/__snapshots__/ListSection.test.js.snap
  typings/components/List.d.ts
Labels: core team

#936 chore: remove TS test generation from CI, fix ts gen script, add tests
  .gitignore
  __ts-tests__/ActivityIndicator.test.tsx
  __ts-tests__/Appbar.test.tsx
  __ts-tests__/AppbarHeader.test.tsx
  __ts-tests__/AvatarIcon.test.tsx
  __ts-tests__/AvatarImage.test.tsx
  __ts-tests__/AvatarText.test.tsx
  __ts-tests__/Badge.test.tsx
  __ts-tests__/Banner.test.tsx
  __ts-tests__/BottomNavigation.test.tsx
  __ts-tests__/Button.test.tsx
  __ts-tests__/Caption.test.tsx
  __ts-tests__/Card.test.tsx
  __ts-tests__/CardActions.test.tsx
  __ts-tests__/CardContent.test.tsx
  __ts-tests__/CardCover.test.tsx
  __ts-tests__/CardTitle.test.tsx
  __ts-tests__/Checkbox.test.tsx
  __ts-tests__/Chip.test.tsx
  __ts-tests__/DataTable.test.tsx
  __ts-tests__/Dialog.test.tsx
  __ts-tests__/DialogActions.test.tsx
  __ts-tests__/DialogContent.test.tsx
  __ts-tests__/DialogScrollArea.test.tsx
  __ts-tests__/DialogTitle.test.tsx
  __ts-tests__/Divider.test.tsx
  __ts-tests__/DrawerItem.test.tsx
  __ts-tests__/DrawerSection.test.tsx
  __ts-tests__/FAB.test.tsx
  __ts-tests__/FABGroup.test.tsx
  __ts-tests__/Headline.test.tsx
  __ts-tests__/HelperText.test.tsx
  __ts-tests__/IconButton.test.tsx
  __ts-tests__/ListAccordion.test.tsx
  __ts-tests__/ListIcon.test.tsx
  __ts-tests__/ListItem.test.tsx
  __ts-tests__/ListSection.test.tsx
  __ts-tests__/ListSubheader.test.tsx
  __ts-tests__/Modal.test.tsx
  __ts-tests__/Paragraph.test.tsx
  __ts-tests__/Portal.test.tsx
  __ts-tests__/PortalHost.test.tsx
  __ts-tests__/ProgressBar.test.tsx
  __ts-tests__/RadioButton.test.tsx
  __ts-tests__/RadioButtonGroup.test.tsx
  __ts-tests__/Searchbar.test.tsx
  __ts-tests__/Snackbar.test.tsx
  __ts-tests__/Subheading.test.tsx
  __ts-tests__/Surface.test.tsx
  __ts-tests__/Switch.test.tsx
  __ts-tests__/TextInput.test.tsx
  __ts-tests__/Title.test.tsx
  __ts-tests__/ToggleButton.test.tsx
  __ts-tests__/ToggleButtonGroup.test.tsx
  __ts-tests__/index.test.tsx
  package.json
  scripts/generate-ts-tests.js
  src/components/HelperText.js
  src/components/List/ListSection.js
  src/components/Portal/Portal.js
Labels: core team

#882 Split TextInput into TextInputOutlined and TextInputFlat
  src/components/TextInput/TextInput.js
  src/components/TextInput/TextInputFlat.js
  src/components/TextInput/TextInputOutlined.js
  src/components/TextInput/types.js
  src/index.js
Labels: TextInput: Refactor, core team, high priority

#485 feat: Menu component
  docs/assets/screenshots/menu-1.png
  docs/assets/screenshots/menu-2.png
  example/src/ExampleList.js
  example/src/Examples/MenuExample.js
  src/components/Menu/Menu.js
  src/components/Menu/MenuItem.js
  src/index.js
  typings/components/Menu.d.ts
  typings/index.d.ts
Labels: high priority

#934 fix: hide banner when visible prop is false
  src/components/Banner.js
  src/components/__tests__/__snapshots__/Banner.test.js.snap
Labels: core team
