Repository callstack/react-native-paper, pull requests merged in 2019-08, with the labels that each got.

#1210 feat: add ability to use own icon component
  example/src/DrawerItems.tsx
  example/src/Examples/ActivityIndicatorExample.tsx
  example/src/Examples/AppbarExample.tsx
  example/src/Examples/BadgeExample.tsx
  example/src/Examples/BannerExample.tsx
  example/src/Examples/BottomNavigationExample.tsx
  example/src/Examples/ButtonExample.tsx
  example/src/Examples/CardExample.tsx
  example/src/Examples/ChipExample.tsx
  example/src/Examples/FABExample.tsx
  example/src/Examples/IconButtonExample.tsx
  example/src/Examples/ListSectionExample.tsx
  example/src/Examples/MenuExample.tsx
  example/src/Examples/SearchbarExample.tsx
  example/src/Examples/ToggleButtonExample.tsx
  example/src/index.native.tsx
  example/src/index.tsx
  src/components/Appbar/AppbarBackAction.tsx
  src/components/Button.tsx
  src/components/CheckboxAndroid.tsx
  src/components/CheckboxIOS.tsx
  src/components/Chip.tsx
  src/components/DataTable/DataTablePagination.tsx
  src/components/DataTable/DataTableTitle.tsx
  src/components/FAB/FAB.tsx
  src/components/FAB/FABGroup.tsx
  src/components/Icon.tsx
  src/components/IconButton.tsx
  src/components/List/ListAccordion.tsx
  src/components/MaterialCommunityIcon.tsx
  src/components/RadioButtonIOS.tsx
  src/components/Searchbar.tsx
  src/components/TextInput/TextInput.tsx
  src/components/__tests__/Appbar/__snapshots__/Appbar.test.js.snap
  src/components/__tests__/Avatar.test.js
  src/components/__tests__/BottomNavigation.test.js
  src/components/__tests__/Button.test.js
  src/components/__tests__/Chip.test.js
  src/components/__tests__/DrawerItem.test.js
  src/components/__tests__/FAB.test.js
  src/components/__tests__/IconButton.test.js
  src/components/__tests__/ListItem.test.js
  src/components/__tests__/ToggleButton.test.js
  src/components/__tests__/__snapshots__/Avatar.test.js.snap
  src/components/__tests__/__snapshots__/BottomNavigation.test.js.snap
  src/components/__tests__/__snapshots__/Button.test.js.snap
  src/components/__tests__/__snapshots__/Checkbox.test.js.snap
  src/components/__tests__/__snapshots__/Chip.test.js.snap
  src/components/__tests__/__snapshots__/DataTable.test.js.snap
  src/components/__tests__/__snapshots__/DrawerItem.test.js.snap
  src/components/__tests__/__snapshots__/FAB.test.js.snap
  src/components/__tests__/__snapshots__/IconButton.test.js.snap
  src/components/__tests__/__snapshots__/ListAccordion.test.js.snap
  src/components/__tests__/__snapshots__/ListItem.test.js.snap
  src/components/__tests__/__snapshots__/ListSection.test.js.snap
  src/components/__tests__/__snapshots__/RadioButton.test.js.snap
  src/components/__tests__/__snapshots__/Searchbar.test.js.snap
  src/components/__tests__/__snapshots__/ToggleButton.test.js.snap
  src/core/Provider.tsx
  src/core/settings.tsx
Labels: 3.0, core team

#1240 chore: update release-it dep from 7.x to 12.x
  .release-it.json
  package.json
  yarn.lock
Labels: core team

#1257 feat: handle fontWeight style-prop
  src/components/TextInput/Label/InputLabel.tsx
  src/components/TextInput/TextInputFlat.tsx
  src/components/TextInput/TextInputOutlined.tsx
  src/components/TextInput/types.tsx
Labels: core team

#1287 docs: update font section according to v3.0
  docs/assets/styles.css
  docs/pages/3.icons.mdx
  docs/pages/5.react-native-web.md
  docs/pages/src/components/IconsList.js
Labels: docs

#1295 fix: change chip close icon to material community icon
  src/components/Chip.tsx
  src/components/__tests__/__snapshots__/Chip.test.js.snap
Labels: waiting response
